# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161007_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='click_rate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='put_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, choices=[('tech', 'Tech'), ('life', 'Life')], max_length=5),
        ),
    ]
