# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161007_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.Article'),
            preserve_default=False,
        ),
    ]
