# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_comment_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.FileField(null=True, upload_to='art_img'),
        ),
    ]
