# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_userprofile_last_visit_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_visit_dt',
            field=models.DateTimeField(),
        ),
    ]
