# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_userprofile_full_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tikcet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('normal', 'Normal')], max_length=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='app.Article')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_tickets', to='app.UserProfile')),
            ],
        ),
    ]
