# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_tikcet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tikcet',
            old_name='voter',
            new_name='user_profile',
        ),
    ]
