# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20161014_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tikcet',
            old_name='user_profile',
            new_name='voter',
        ),
    ]
