# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20161014_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='collector',
            field=models.ManyToManyField(related_name='collections', to='app.UserProfile'),
        ),
    ]
