# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_article_collector'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('female', '\u5973'), ('male', '\u7537'), ('secret', '\u4fdd\u5bc6')], max_length=10, null=True),
        ),
    ]
